version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: hiatto-backend
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx-backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-backend
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiatto_database
      MYSQL_USER: hiatto
      MYSQL_PASSWORD: hiatto@2025
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
